behaviors:
  CarAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 18000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      # memory:
      #   sequence_length: 64
      #   memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 2048
    summary_freq: 18000
    checkpoint_interval: 50000